In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from TAS_Python_Utilities import data_viz
from TAS_Python_Utilities import data_viz_target
from TAS_Python_Utilities import visualize_tree

from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn import ensemble
from sklearn import linear_model
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# import os
# import subprocess
# from IPython.display import display, HTML, Image
# import io
# from operator import itemgetter

# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt

# #from TAS_Python_Utilities import data_viz
# #from TAS_Python_Utilities import data_viz_target
# #from TAS_Python_Utilities import visualize_tree

# from sklearn.tree import export_graphviz
# from sklearn import tree
# from sklearn import metrics
# from sklearn import tree
# from sklearn import svm
# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import cross_val_score
# from sklearn.model_selection import train_test_split
# from mlxtend.feature_selection import SequentialFeatureSelector as SFS
# from sklearn import ensemble
# from sklearn import linear_model
# from sklearn import neighbors

# #from xgboost import XGBClassifier

# %matplotlib inline
# %qtconsole

In [2]:
dataset = pd.read_csv('fashion-mnist_train.csv')
dataset.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
dataset["label"].value_counts()

9    6000
8    6000
7    6000
6    6000
5    6000
4    6000
3    6000
2    6000
1    6000
0    6000
Name: label, dtype: int64

In [4]:
display(dataset.select_dtypes(include=[np.number]).describe())

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,...,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.00000
mean,4.500000,0.000900,0.006150,0.035333,0.101933,0.247967,0.411467,0.805767,2.198283,5.682000,...,34.625400,23.300683,16.588267,17.869433,22.814817,17.911483,8.520633,2.753300,0.855517,0.07025
std,2.872305,0.094689,0.271011,1.222324,2.452871,4.306912,5.836188,8.215169,14.093378,23.819481,...,57.545242,48.854427,41.979611,43.966032,51.830477,45.149388,29.614859,17.397652,9.356960,2.12587
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,4.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,58.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,9.000000,16.000000,36.000000,226.000000,164.000000,227.000000,230.000000,224.000000,255.000000,254.000000,...,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,170.00000

In [5]:
X=dataset.drop(columns='label')
Y=dataset['label']

In [6]:
X_train, X_valid, y_train, y_valid \
    = train_test_split(X, Y, random_state=0, \
                            train_size = 0.7)

In [7]:
my_tree = tree.DecisionTreeClassifier(criterion="entropy")
my_tree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [8]:
# Make a set of predictions for the training data
y_pred = my_tree.predict(X_valid)

# Print performance details
accuracy = \
metrics.accuracy_score(y_valid, y_pred) # , normalize=True, sample_weight=None
print("Accuracy: " +  str(accuracy))

print(metrics.classification_report(y_valid, y_pred))

# Print confusion matrix
print(metrics.confusion_matrix(y_valid, y_pred))

# Print nicer homemade confusion matrix
print("Confusion Matrix")
pd.crosstab(y_valid, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Accuracy: 0.8051666666666667
              precision    recall  f1-score   support

           0       0.75      0.76      0.75      1799
           1       0.94      0.94      0.94      1843
           2       0.69      0.71      0.70      1808
           3       0.82      0.80      0.81      1849
           4       0.69      0.68      0.69      1765
           5       0.91      0.90      0.91      1786
           6       0.55      0.55      0.55      1787
           7       0.88      0.88      0.88      1789
           8       0.92      0.92      0.92      1795
           9       0.90      0.91      0.91      1779

    accuracy                           0.81     18000
   macro avg       0.81      0.80      0.80     18000
weighted avg       0.81      0.81      0.81     18000

[[1360   10   40   77   15    4  269    1   23    0]
 [  16 1735   11   50    9    0   18    0    4    0]
 [  39    8 1287   23  212    0  222    0   16    1]
 [  79   57   32 1477  106    2   77    0   17    2]
 [  17    6  241   98 1205    0  186    0   12    0]
 [   0    2    3    1    1 1610    0   91   28   50]
 [ 282   17  227   63  183    4  974    0   37    0]
 [   0    0    0    0    0   83    0 1580    5  121]
 [  16    3   21   21   18   19   34   11 1645    7]
 [   1    0    0    0    0   38    2  114    4 1620]]
Confusion Matrix

Predicted     0     1     2     3     4     5     6     7     8     9    All
True
0          1360    10    40    77    15     4   269     1    23     0   1799
1            16  1735    11    50     9     0    18     0     4     0   1843
2            39     8  1287    23   212     0   222     0    16     1   1808
3            79    57    32  1477   106     2    77     0    17     2   1849
4            17     6   241    98  1205     0   186     0    12     0   1765
5             0     2     3     1     1  1610     0    91    28    50   1786
6           282    17   227    63   183     4   974     0    37     0   1787
7             0     0     0     0     0    83     0  1580     5   121   1789
8            16     3    21    21    18    19    34    11  1645     7   1795
9             1     0     0     0     0    38     2   114     4  1620   1779
All        1810  1838  1862  1810  1749  1760  1782  1797  1791  1801  18000

In [ ]:
my_tree = tree.DecisionTreeClassifier(max_depth = 12)
scores = cross_val_score(my_tree, X, Y, cv=5)
print(scores)
scores = pd.Series(scores)
print(scores.mean(), " =/- ", scores.std())

# Grid Search

In [ ]:
# Set up the parameter grid to seaerch
param_grid ={'criterion': ['gini', "entropy"], \
             'max_depth': list(range(3, 20, 3)), \
             'min_samples_split': [50] }

# Perform the search
my_tuned_tree = GridSearchCV(tree.DecisionTreeClassifier(), \
                                param_grid, cv=2, verbose = 0, \
                            return_train_score=True)
my_tuned_tree.fit(X, Y)

# Print details
print("Best parameters set found on development set:")
display(my_tuned_tree.best_params_)
display(my_tuned_tree.best_score_)
display(my_tuned_tree.cv_results_)

### Evaluation on the test set

In [ ]:
test_set = dataset = pd.read_csv('fashion-mnist_test.csv')
test_set.head()

In [ ]:
X_test=test_set.drop(columns='label')
Y_test=test_set['label']

In [ ]:
# Make a set of predictions for the test data
y_pred = my_tuned_tree.predict(X_test)

# Print performance details
print(metrics.classification_report(Y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix")
pd.crosstab(Y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

# Random Forest

In [ ]:
# Do the same job with random forests
my_model_RF = ensemble.RandomForestClassifier(n_estimators=300, \
                                           max_features = 3,\
                                           min_samples_split=200)
my_model_RF.fit(X,Y)

In [ ]:
# Make a set of predictions for the test data
y_pred = my_model_RF.predict(X_valid)

# Print performance details
print(metrics.classification_report(y_valid, y_pred))

# Print confusion matrix
print("Confusion Matrix")
pd.crosstab(y_valid, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

# Bagging

In [ ]:
# Do the same job with bagging
my_model_bag = ensemble.BaggingClassifier(base_estimator = tree.DecisionTreeClassifier(criterion="entropy", min_samples_leaf = 50), \
                                      n_estimators=10)
my_model_bag.fit(X,Y)

In [ ]:
# Make a set of predictions for the test data
y_pred = my_model_bag.predict(X_valid)

# Print performance details
print(metrics.classification_report(y_valid, y_pred))

# Print confusion matrix
print("Confusion Matrix")
pd.crosstab(y_valid, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

# Boosting

In [ ]:
# Do the same job with boosting
my_model_boost = ensemble.AdaBoostClassifier(base_estimator = tree.DecisionTreeClassifier(criterion="entropy", min_samples_leaf = 50), \
                                       n_estimators=10)
my_model_boost.fit(X_train,y_train)

In [ ]:
# Make a set of predictions for the test data
y_pred = my_model_boost.predict(X_valid)

# Print performance details
print(metrics.classification_report(y_valid, y_pred))

# Print confusion matrix
print("Confusion Matrix")
pd.crosstab(y_valid, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

# Logistic Regression

In [ ]:
# Do the same job with logistic regression
my_model_Lr = linear_model.LogisticRegression()
my_model_Lr.fit(X,Y)

In [ ]:
# Make a set of predictions for the test data
y_pred = my_model_Lr.predict(X_valid)

# Print performance details
print(metrics.classification_report(y_valid, y_pred))

# Print confusion matrix
print("Confusion Matrix")
pd.crosstab(y_valid, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

### using dimeantionality reduction as a feature enginnering

In [7]:
X_scaler = StandardScaler().fit_transform(X)

In [8]:
pcafit = PCA(n_components=36)
X_pca = pcafit.fit(X_scaler).transform(X)
pcafit.explained_variance_ratio_

array([0.22057176, 0.14395563, 0.05458802, 0.05116399, 0.04069273,
       0.03012154, 0.02750481, 0.02325871, 0.01694438, 0.01309833,
       0.01161488, 0.00963108, 0.00890642, 0.00856623, 0.00743049,
       0.00730157, 0.00657498, 0.00632692, 0.00623657, 0.0058046 ,
       0.00515706, 0.00511546, 0.00472763, 0.00453552, 0.00438381,
       0.00416775, 0.00394976, 0.00393163, 0.00378242, 0.0037436 ,
       0.00368413, 0.0035332 , 0.00336131, 0.00329383, 0.00329121,
       0.00319102])

In [9]:
X_train_pca, X_valid_pca, y_train_pca, y_valid_pca \
    = train_test_split(X_pca, Y,  random_state=0, \
                                        train_size = 0.7)

In [10]:
# Do the same job with logistic regression
my_model_pca = linear_model.LogisticRegression()
my_model_pca.fit(X_pca,Y)

C:\Users\susmi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\susmi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\susmi\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
# Make a set of predictions for the test data
y_pred = my_model_pca.predict(X_valid_pca)

# Print performance details
print(metrics.classification_report(y_valid_pca, y_pred))

# Print confusion matrix
print("Confusion Matrix")
pd.crosstab(y_valid_pca, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

              precision    recall  f1-score   support

           0       0.78      0.80      0.79      1799
           1       0.96      0.95      0.96      1843
           2       0.72      0.73      0.73      1808
           3       0.79      0.86      0.82      1849
           4       0.68      0.78      0.73      1765
           5       0.91      0.89      0.90      1786
           6       0.61      0.43      0.51      1787
           7       0.88      0.89      0.89      1789
           8       0.91      0.94      0.92      1795
           9       0.92      0.93      0.93      1779

    accuracy                           0.82     18000
   macro avg       0.82      0.82      0.82     18000
weighted avg       0.82      0.82      0.82     18000

Confusion Matrix

Predicted     0     1     2     3     4     5     6     7     8     9    All
True
0          1445     9    25   148     5     4   117     3    42     1   1799
1             1  1760    13    55     2     0    10     0     2     0   1843
2            15     6  1323    10   284     0   145     2    23     0   1808
3            61    29    23  1598    81     1    50     1     5     0   1849
4             4    12   163    83  1368     4   116     0    15     0   1765
5             2     2     3     6     0  1585     5   120    16    47   1786
6           315    11   281    98   254     6   767     0    55     0   1787
7             0     0     0     0     0    98     0  1593     8    90   1789
8             4     1     9    27     6    12    39     7  1687     3   1795
9             0     0     0     2     0    38     1    75     1  1662   1779
All        1847  1830  1840  2027  2000  1748  1250  1801  1854  1803  18000

### Testing the model using the test set with the pca andlogistic regression

In [15]:
data_test_set = pd.read_csv('fashion-mnist_test.csv')
data_test_set.head()
X_test = data_test_set.drop(columns='label')
Y_test = data_test_set['label']

In [16]:
X_scaler_test = StandardScaler().fit_transform(X_test)
pcafit = PCA(n_components=36)
X_pca_test = pcafit.fit(X_scaler_test).transform(X_test)

In [17]:
# Make a set of predictions for the test data
y_pred = my_model_pca.predict(X_pca_test)

# Print performance details
accuracy = metrics.accuracy_score(Y_test, y_pred) # , normalize=True, sample_weight=None
print("Accuracy: " +  str(accuracy))
print(metrics.classification_report(Y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix")
pd.crosstab(Y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True)

Accuracy: 0.4479
              precision    recall  f1-score   support

           0       0.56      0.63      0.59      1000
           1       0.70      0.93      0.80      1000
           2       0.50      0.25      0.33      1000
           3       0.59      0.43      0.50      1000
           4       0.48      0.24      0.32      1000
           5       0.22      0.56      0.32      1000
           6       0.41      0.34      0.37      1000
           7       0.32      0.19      0.24      1000
           8       0.48      0.75      0.58      1000
           9       0.59      0.16      0.25      1000

    accuracy                           0.45     10000
   macro avg       0.49      0.45      0.43     10000
weighted avg       0.49      0.45      0.43     10000

Confusion Matrix

Predicted     0     1    2    3    4     5    6    7     8    9    All
True
0           627    58   28  167    5    22   31    6    55    1   1000
1             8   930   11   16    0    19    6    5     5    0   1000
2            27    62  247    7  188   102  222    1   144    0   1000
3           200   224    8  430    1    20   48    8    57    4   1000
4            51    25   96    8  240    81  168    0   330    1   1000
5             2     0    3    1    8   564    0  314    58   50   1000
6           194    30   90   76   49    94  340    3   124    0   1000
7             1     0    0    0    0   714    0  192    40   53   1000
8             0     3    6   19    5   193   10   12   750    2   1000
9             0     0    1    0    0   760    0   66    14  159   1000
All        1110  1332  490  724  496  2569  825  607  1577  270  10000